### PR TITLE
Enable toc org for markdown

### PR DESCRIPTION
**Pull request by snosov1**

### CODE REVIEW

**Comment by snosov1** [comment]
I decided that this mode needs a new major feature to celebrate its 5-year anniversary. And what can be more major than the support for a completely new markup syntax?! So, I fixed a couple of regexps and now `toc-org` can be enabled in Markdown files! It seems to work on my end and now I call to you, `toc-org`'s trusty contributors - @alphapapa, @JAremko, @ardumont, @iqbalansari, @azizyemloul - do you, guys, care to give it a spin before I merge to master?

**Comment by alphapapa** [comment]
Cool!  I'm sure a lot of people will find this useful.  You may need to rename the package, though, otherwise people won't expect it to support Markdown.  ;)

**Comment by iqbalansari** [comment]
Nice, I wonder how this compare to the existing [markdown-toc](https://github.com/ardumont/markdown-toc). Are there plans to generalize the underlying code to be able to support multiple formats, like @alphapapa suggests?

**Comment by snosov1** [comment]
> You may need to rename the package, though, otherwise people won't expect it to support Markdown. ;)

No way - one rename of the module (from `org-toc` to `toc-org`) was more than enough for me =) The documentation should make it clear.

> Then they could both be part of the toc-x family of packages. :)

A little bit far-fetching for a tiny text parsing module of mine =)

> Nice, I wonder how this compare to the existing markdown-toc. 

I think it should be fairly similar in functionality. But, at least to me, `toc-org`'s design seems a little bit more "seamless" and I've added the support for following links (mimics org's `C-c C-o` binding). 

Anyway, have you, guys, actually, tried it? Found any bugs/glitches?

**Pull request merged**
